#!/bin/bash
# comparision of the two user number

echo  "enter first number"
read a
echo "enter 2nd numbr"
read b
if [ $a -eq $b ]
then 
  echo " both are equal"

elif [ $a -gt $b ]
then
 echo " $a is greater then $b"

else
  echo "$a is less than $b"
fi
